Tailwind styling tweaks
yext/react-site-search-starter pull request #22
Opened 2021-12-23 22:19 UTC by nmanu1

Use 'cursor-pointer' for FilterSearch results and make other small adjustments to tailwind styling for other components.

J=SLAP-1772
TEST=manual

Check that cursor becomes a pointer on FilterSearch results and that other tweaks match mocks.

2022-01-03 13:34 UTC, tmeyer2115 approved these changes

2022-01-03 13:35 UTC, tmeyer2115 commented
Once you fix the merge conflict, lemme know and I can take another look!

2022-01-04 15:34 UTC, tmeyer2115 approved these changes

2022-01-04 15:36 UTC, tmeyer2115 commented
I think some WCAG issues were introduced with this change. Can you investigate the test failures?

2022-01-04 15:37 UTC, tmeyer2115 requested changes
This PR seems to have introduced some WCAG issues. Can you investigate those?

2022-01-04 15:43 UTC, cea2aj commented on src/components/utils/renderCheckboxOption.tsx
> +  optionLabel: 'text-gray-500 text-sm font-normal'
The mock calls for text-gray-500, however we intentionally bumped it to 600 to improve the text contrast. This may be related to the WCAG issue

2022-01-04 16:06 UTC, nmanu1 commented on src/components/utils/renderCheckboxOption.tsx
> +  optionLabel: 'text-gray-500 text-sm font-normal'
Got it! Changed it back

2022-01-04 16:57 UTC, cea2aj commented on src/components/SearchBar.tsx
> +  container: 'h-12 mb-3',
I believe that 'mb-4' is more accurate to the mocks because the mocks show spacing of 32px between the search bar and the nav text. Are you changing it because it looks a little closer to the mocks?

2022-01-04 17:05 UTC, nmanu1 commented on src/components/SearchBar.tsx
> +  container: 'h-12 mb-3',
Yes, I was changing it to look a little closer to the mocks because I think `h-12` is also adding some space between the search bar and nav text

2022-01-04 17:11 UTC, cea2aj commented on src/components/SearchBar.tsx
> +  container: 'h-12 mb-3',
That makes sense. `mb-3` does look closer to the mocks

2022-01-04 17:11 UTC, cea2aj submitted a review, later dismissed

2022-01-04 17:14 UTC, cea2aj commented on src/components/FilterSearch.tsx
>    inputElement: 'text-sm bg-white outline-none h-9 w-full p-1 rounded-md border border-gray-300 focus:border-blue-600',
Slightly unrelated, but while we're here can we update the `inputElement` padding to `px-2`? I think it looks closer to the mocks

2022-01-04 17:32 UTC, nmanu1 commented on src/components/FilterSearch.tsx
>    inputElement: 'text-sm bg-white outline-none h-9 w-full p-1 rounded-md border border-gray-300 focus:border-blue-600',
Yes, I agree, that looks closer to the mocks even though the mocks show a spacing of 8px. But maybe `p-2` would be better to keep the padding on the top and bottom as well

2022-01-04 17:56 UTC, tmeyer2115 approved these changes

2022-01-04 19:46 UTC, nmanu1 commented on src/components/utils/renderCheckboxOption.tsx
> +  optionLabel: 'text-gray-500 text-sm font-normal'
Ended up using `text-gray-500` to match the mocks because the text contrast is sufficient and it wasn't causing the WCAG issue

2022-01-04 20:04 UTC, cea2aj approved these changes

2022-01-04 20:11 UTC, merged